# Generated by Django 4.1.3 on 2022-11-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('lat', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='author',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('member', 'участник'), ('moderator', 'модератор'), ('admin', 'админ')], max_length=9, verbose_name='Роль')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('location', models.ManyToManyField(to='ads.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.user'),
        ),
    ]
