# Generated by Django 4.1.3 on 2022-11-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_location_remove_advertisement_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='category_id',
            new_name='category',
        ),
    ]
