# Generated by Django 4.1.3 on 2022-11-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_category_id_advertisement_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_id',
            new_name='author',
        ),
    ]
