# Generated by Django 4.1.3 on 2022-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_author_id_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='ads.location', verbose_name='Локация'),
        ),
    ]
