# Generated by Django 4.1.3 on 2022-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='address',
        ),
    ]
