# Generated by Django 4.1.3 on 2022-11-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='locations',
        ),
    ]
